apps/_docs/content/docs/dark-mode.mdx
apps/_docs/content/docs/meta.json
apps/app/app/(authenticated)/components/sidebar.tsx
apps/app/app/(unauthenticated)/sign-in/[[...sign-in]]/page.tsx
apps/app/app/(unauthenticated)/sign-up/[[...sign-up]]/page.tsx
apps/app/app/layout.tsx
apps/web/app/components/footer.tsx
apps/web/app/components/header/index.tsx
packages/design-system/components/mode-toggle.tsx
packages/design-system/lib/tailwind.ts
packages/design-system/package.json
packages/design-system/providers/clerk.tsx
packages/design-system/tailwind.config.ts
pnpm-lock.yaml

This pull request introduces dark mode support across the application by integrating Tailwind CSS and `next-themes`. Key changes include the addition of a `ModeToggle` component, updates to various pages and components to support dark mode, and configuration adjustments to accommodate the theme changes.
* [`apps/_docs/content/docs/dark-mode.mdx`](diffhunk://#diff-0f58ecacf1d902c87978a0526666db2349dabf74188ed20ddf76d841895029aeR1-R37): Added documentation for dark mode implementation using Tailwind's `darkMode: 'class'` strategy and `next-themes`.
* [`packages/design-system/components/mode-toggle.tsx`](diffhunk://#diff-c57cc9429d8e57e2361b2f9bdc18653a8571e15b1c94b8ba07675dd6e805efd3R1-R45): Created `ModeToggle` component to allow users to switch between light, dark, and system themes.
* …

Improve Dark Mode support

---

apps/_docs/content/docs/database.mdx

this PR includes:
- a minor fix in the "switch to PlanetScale" guide to add `[!code --]` on the `import ws from 'ws'; //` in the PlanetScale guide
- a guide for switching to Prisma Postgres (incl some notes about using caching and real-time events)

add docs for switching to Prisma Postgres

---

apps/_docs/app/docs/[[...slug]]/page.tsx
apps/_docs/app/docs/components/coauthors.tsx
apps/_docs/content/docs/drizzle.mdx
apps/_docs/content/docs/meta.json
apps/_docs/content/docs/planetscale.mdx
apps/_docs/next.config.mjs

This pull request includes updates to the documentation for switching databases in the `next-forge` project. The primary focus is on adding a guide for switching from Prisma to Drizzle and renaming the existing database guide to focus on PlanetScale.

Co-author: Drizzle

---

docs/overview.mdx

- Fixed typo by removing duplicate word "is"
- Changed "it is is a" to "it is a"

fix: Remove duplicate "is" in text

---

docs/setup.mdx

Updates the docs to list the accounts needed to use Next Forge.

List the required accounts in setup

---

tsconfig.json

A root tsconfig.json in a Workspace doesn't do anything if there isn't any TypeScript code in the root (which there shouldn't be). Packages set their own TypeScript settings in their own `tsconfig.json`.

Remove root tsconfig.json

---

packages/design-system/components/ui/sidebar.tsx

Add a <SheetTitle /> component to the mobile sidebar that is only visual to screen readers.
I made the title screen reader only. There may be a better default.

fix: add sheet title for a11y.

---

apps/api/app/webhooks/clerk/route.ts
apps/api/app/webhooks/stripe/route.ts
apps/api/package.json
apps/app/app/(authenticated)/components/posthog-identifier.tsx
apps/app/app/(authenticated)/components/sidebar.tsx
apps/app/app/(authenticated)/layout.tsx
apps/app/app/(authenticated)/page.tsx
apps/app/app/actions/users/get.ts
apps/app/app/actions/users/search.ts
apps/app/app/api/collaboration/auth/route.ts
apps/app/middleware.ts
apps/app/package.json
apps/web/middleware.ts
apps/web/package.json
docs/authentication/authjs.mdx
docs/authentication/overview.mdx
docs/mint.json
packages/auth/client.ts
packages/auth/middleware.ts
packages/auth/package.json
packages/auth/server.ts
packages/feature-flags/lib/create-flag.ts
packages/feature-flags/package.json
packages/webhooks/lib/svix.ts
packages/webhooks/package.json
pnpm-lock.yaml

Resolves #239 
Blocked by https://github.com/nextauthjs/next-auth/issues/11076

Create Auth.js migration guide

---

apps/web/app/components/header/index.tsx

App: `web`
Running the initial app in development mode and hovering over the **Products** link triggers an error. The issue arises from iterating over submenu links using duplicate keys. (More info on the screenshot below)
There are three potential solutions:
1. Use the second argument of the `map` method (index) as a key: I opted for this approach since the submenu items are static and not intended to be dynamically changed. This is the most straightforward and context-appropriate fix.
2. Rename the links: While this resolves the duplication, it’s misleading in this case because all links point to the same destination (Pricing). Renaming them adds unnecessary confusion.
3. Enrich the links structure by adding an `id` property. Personally, I find this unnecessary. In real-world usage, …

fix: resolve submenu duplication issues by using index as a key

---

docs/authentication/authjs.mdx

If I copy and paste all the suggested commands, from the second command
I'd get the error message "no such directory" on `cd apps/web`.
None
N/A

Minor: fix authjs migration secrets creation command

---

docs/migrations/payments/lemon-squeezy.mdx
docs/mint.json

This pull request includes documentation updates to guide users on switching the default payment processor from Stripe to Lemon Squeezy. The most important changes include detailed instructions on updating dependencies, environment variables, the payments client, and the webhook handler, as well as adding a new section to the documentation index.
Documentation updates:
* [`docs/migrations/payments/lemon-squeezy.mdx`](diffhunk://#diff-b56e3cad2fa52f16ad997322dbae60a9a38f8d1f14347fc76731da159049304cR1-R91): Added a new guide on how to switch the default payment processor to Lemon Squeezy, including steps for updating dependencies, environment variables, the payments client, and the webhook handler.
Index updates:
* [`docs/mint.json`](diffhunk://#diff-c91a604899dfef4b2494c317f4fd39a7f22b79986 …

Add Lemon Squeezy guide

---

docs/migrations/database/drizzle.mdx

Fixes #340
Update the Drizzle migration documentation to include missing package and environment configuration steps.
* Add a step to install `@neondatabase/serverless` package in the `docs/migrations/database/drizzle.mdx` file.
* Change the `databaseUrl` to the `DATABASE_URL` environment variable in the `drizzle.config.ts` file.
* Add a step to update the migration script in the root `package.json` from Prisma to Drizzle in the `docs/migrations/database/drizzle.mdx` file.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/haydenbleasel/next-forge/pull/341?shareId=29a8caf4-b759-46d3-aab2-7aae3f5811da).

Update Drizzle migration documentation

---

apps/app/middleware.ts
apps/app/package.json
apps/web/middleware.ts
docs/features/security/headers.mdx
packages/next-config/index.ts
packages/next-config/package.json
packages/security/middleware.ts
packages/security/package.json
pnpm-lock.yaml

next-secure-headers hasn't been updated for 3 years and is setting obsolete security headers. We just released [Nosecone](https://docs.arcjet.com/nosecone/quick-start) which is an open source library for configuring security headers like CSP and HSTS on Next.js and other frameworks.
As discussed in the PR, CSP is not set by default. We can revisit when https://github.com/haydenbleasel/next-forge/pull/332 is done. There is a working example config in the docs.
Loading http://localhost:3000/sign-in sets the following headers:
```
Cache-Control: no-store, must-revalidate
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Date: Tue, 10 Dec 2024 18:48:01 GMT
Keep-Alive: timeout=5
Link: </_next/static/media/GeistMono_Variable.p.0ce97b8a.woff2>; rel=preload; …
```

Replace next-secure-headers with Nosecone for security headers

---

docs/features/storage.mdx
docs/migrations/storage/upload-thing.mdx
docs/mint.json

This pull request includes several updates to the documentation and migration guides for the `storage` package. The most important changes include adding new sections for server and client uploads, creating a detailed migration guide for switching to `uploadthing`, and updating the `mint.json` configuration to include the new migration guide.
Documentation updates:
* [`docs/features/storage.mdx`](diffhunk://#diff-62551fb3fab0ebe3b37370f8beefa4563b34ed8a22fb8364c4b6ad706e539cd4R10-R15): Added new sections for server uploads and client uploads, including tips and updated import paths. [[1]](diffhunk://#diff-62551fb3fab0ebe3b37370f8beefa4563b34ed8a22fb8364c4b6ad706e539cd4R10-R15) [[2]](diffhunk://#diff-62551fb3fab0ebe3b37370f8beefa4563b34ed8a22fb8364c4b6ad706e539cd4R39-R42)
Migration guide: …

Add uploadthing migration guide

---

apps/api/vercel.json
docs/features/cron.mdx

With current setup, "vercel link" returns "Error: Hobby accounts are limited to daily cron jobs. This cron expression (*/10 * * * *) would run more than once per day. Upgrade to pro to unlock all Cron Jobs features on Vercel."
`https://crontab.guru/#0_1_*_*_*` = “At 01:00.”
None

Change Cron to daily to allow vercel hobby projects

---

scripts/init.mjs

This PR insures the initialization script (`scripts/init.mjs`) works when running `npx next-forge@latest init [my-app] --package-manager bun
`, currently install fails due to the way bun requires the workspaces to be defined in package.json:
1. Improves Bun workspace configuration by:
- Adding proper workspace configuration to package.json
- Removing pnpm-specific workspace files when Bun is selected
- Setting the correct package manager field in package.json
2. Fixes package manager script execution by ensuring the `run` command is included for all package managers (npm, yarn, pnpm, and bun) when executing build scripts
NA
- Modified the Prisma build command in `scripts/init.mjs` to consistently use `run` with all package managers
- Changed `${packageManager} build --filter …

Fix: This fixes the bun install failure when opting for bun

---

scripts/init.mjs

This pull request includes updates to the `scripts/init.mjs` file to improve the initialization process for new projects. The changes primarily focus on updating the commands for different package managers and refining the configuration steps.
Resolves #394

Fix installation for non-pnpm package managers

---

docs/migrations/formatting/eslint.mdx

I noticed eslint-plugin-next is an empty package, but next.js is @next/eslint-plugin-next. 
| eslint-plugin-next                                           | @next/eslint-plugin-next                                     |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| <img width="505" alt="image" src="https://github.com/user-attachments/assets/0457fcc2-42e6-48b5-a81c-25d1871f9c0d" /> | <img width="466" alt="image" src="https://github.com/user-attachments/assets/1f4b7441-0c90-452e-95e3-98ae0eeb639a" /> |

Imporve document for ESLint configuration

---

docs/updates.mdx
scripts/initialize.ts
scripts/update.ts
scripts/utils.ts

I was thinking it might be easier for users to be given a list of all the available versions they can update to rather then them looking for which ones are available. Will give devs easier/faster experience so they don't have to search for too long. This gets the current version from the package.json and compares it to the changelog.md file
Was also thinking of a way to add small descriptions on the versions. Kind of an all in one spot but might be too crowded with that much info.
N/A
If a user have available versions to update to:
```
┌  Let's update your next-forge project!
│
●  Current version: v3.2.10
│
◆  Select a version to update to:
│  ● v3.2.15
│  ○ v3.2.14
│  ○ v3.2.13
│  ○ v3.2.12
│  ○ v3.2.11
└
```
If a user is already on the latest versionL
```
┌  Let's update your next-forge …
```

Enhance CLI command - Update  

---

apps/app/app/(authenticated)/components/sidebar.tsx

Use Next.js [Link component](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#link-component) for sidebar navigation.

feat: Use Link component for sidebar links

---

packages/cms/package.json

Invalid build script within /packages/cms. Solution: add "build" after "basehub".

fix error: build script in /packages/cms

---

apps/web/app/[locale]/legal/[slug]/page.tsx
packages/cms/components/body.tsx

[Fixed issue #500](https://github.com/haydenbleasel/next-forge/issues/500)
When rendering the [Table of Contents](https://github.com/haydenbleasel/next-forge/blob/main/packages/cms/components/toc.tsx), the RichText component is receiving an 'isTasksList' prop that ends up on a native ul element. React then warns that this prop is not recognized as a valid DOM attribute. If you intentionally need a custom attribute, it should be lowercase like 'istaskslist', or it should be removed from the DOM element.
I just provided a custom component for the RichText like how it is in the blog/[slug]/page.tsx. I am now working with basehub v8.1.31. Here's the code I used:
```
<Body 
content={page.body.json.content}
components={{
ul: ({ children, isTasksList, ...props }) => (
<ul …
```

Fixed Issue #500

---

packages/design-system/styles/globals.css

Realized the globals.css file was missing `success` color variable which in turn couldn't be used
- [x ] My code follows the code style of this project.
- [] New and existing tests pass locally with my changes.
Despite the class showing in the code, it's still not picking up the color—maybe I've missed something?

fix: add success color variable

---

packages/seo/metadata.ts

Error in the logs when building:
```
⚠ metadataBase property in metadata export is not set for resolving social open graph or twitter images, using "https://trimcarbon.com". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
```
I'd also suggest editing robots.ts to use https:// by default as Vercel var doesn't include https:// https://vercel.com/docs/environment-variables/system-environment-variables#VERCEL_PROJECT_PRODUCTION_URL (and thus the logic will always be outputting http).

fix: metadataBase

---

apps/web/app/[locale]/components/header/language-switcher.tsx

Noticed the language switcher was only working from other locales > english or other locales > other locales. 
Because /en wasn't in the pathname, the router was pushing the same url (as there was nothing to replace).
See recording:
See after change (recorded on my own project for simplicity):

fix: language switcher

---

apps/email/package.json

- Added `--dir` flag to `build` and `export` scripts in apps/email/package.json
- Points to the correct email templates location at `../../packages/email/templates`
- Matches the existing configuration in the `dev` script
The email app build was failing because the react-email CLI defaults to looking for templates in `./emails` relative to where the command runs, but the actual templates are in `packages/email/templates`.
Updated the scripts to explicitly specify the templates directory path using the `--dir` flag.
Fixes #619

fix: add missing --dir flag to email build and export scripts

---

apps/app/app/(unauthenticated)/layout.tsx

The toggle on (unauthenticated) layout was disappearing when switching—this change prevents that
(do note that in my own version I have a different method for ModeToggle that switches between the theme rather than displaying a dropdown).

fix: better dark/light support on unauthenticated
