vercel/next-forge

apps/app/package.json
pnpm-lock.yaml

This pull request includes a small change to the `package.json` file. The change adds a new dependency to the project.
* [`apps/app/package.json`](diffhunk://#diff-15a93da17a40a2a46b85fb22b881b4f9cf1e3df61f06826a7da6e7daa3ba0c66R18): Added `@repo/env` as a new dependency.

feat: add repo/env to app

---

setup.bat

Add the script setup for windows

chore(windows_setup): add windows setup script

---

apps/docs/mint.json
docs/mint.json

Fix `.font` instructions in docs app

---

docs/database/turso.mdx
docs/mint.json

This adds Turso to the database alternative guides.

feat: add turso guide

---

docs/env.mdx

Updates the docs to better reflect the `.env` file directory location.
N/A
Changes docs from `apps/database` to `packages/database`.

Update location of .env file in directory docs

---

.vscode/extensions.json
.vscode/settings.json

This PR optimizes VSCode settings by merging single language configuration into one, reducing code duplication.
N/A
Docs for this: https://code.visualstudio.com/docs/getstarted/settings#_multiple-languagespecific-editor-settings

VSCode workspace configuration

---

docs/authentication/overview.mdx
docs/collaboration.mdx
docs/flags.mdx
docs/formatting.mdx
docs/payments.mdx
docs/recommended-libraries/friendlier-words.mdx
docs/recommended-libraries/motion.mdx
docs/recommended-libraries/nuqs.mdx
docs/recommended-libraries/react-wrap-balancer.mdx
docs/recommended-libraries/zustand.mdx
docs/storybook.mdx

This pull request introduces built-in components for the docs.
Built-in components and related docs:
- [Frames](https://mintlify.com/docs/content/components/frames)
- [Steps](https://mintlify.com/docs/content/components/steps)
- [Icons](https://mintlify.com/docs/content/components/icons)

feat: Add built-in components for readability

---

docs/authentication/better-auth.mdx

Please provide a brief description of the changes introduced in this pull request.
Closes #<issue_number>
- [ x ] My code follows the code style of this project.
- [ x ] I have performed a self-review of my code.
- [    ] I have commented my code, particularly in hard-to-understand areas.
- [ x ] I have updated the documentation, if necessary.
- [ x ] I have added tests that prove my fix is effective or my feature works.
- [ x ] New and existing tests pass locally with my changes.

feat: added missing imports and fixed speeling

---

apps/app/app/(authenticated)/layout.tsx
apps/web/middleware.ts
packages/security/package.json
pnpm-lock.yaml

Adds logging when Arcjet denies a request so it can be investigated, which will help if https://github.com/haydenbleasel/next-forge/issues/298 comes up again.
Also updates Arcjet SDK and fixes deny logic for rules other than bot detection.

fix: Log Arcjet deny reason

---

apps/storybook/.storybook/preview.tsx

Updated Storybook's background configuration to properly support dark mode themes. This change provides better visual testing environment for dark mode components by setting appropriate background colors that match the design system.
Updated `.storybook/preview.tsx` with the following configuration:
```typescript
import { Toaster } from '@repo/design-system/components/ui/sonner';
import { TooltipProvider } from '@repo/design-system/components/ui/tooltip';
import { ThemeProvider } from '@repo/design-system/providers/theme';
import type { Preview } from '@storybook/react';
import '@repo/design-system/styles/globals.css';
const preview: Preview = {
parameters: {
controls: {
matchers: {
color: /(background|color)$/i,
date: /Date$/i,
},
},
backgrounds: {
default: 'dark',
values: [
{
name: …
```

Set defaults for Shadcn darkmode in Storybook

---

docs/database/turso.mdx

Remove repeated mention of "on-device RAG, local-first vector search" in Turso description.

Improve Grammer in Turso Docs

---

docs/database/overview.mdx
docs/database/supabase.mdx
docs/mint.json
packages/database/index.ts

Please provide a brief description of the changes introduced in this pull request.
* Adds a blog post to include steps to use [Supabase](https://supabase.com)
* Want to add Supabase Auth to the authentication section, but it will need to be a bit more involved to achieve feature parody with organization configuration Clerk provides. But happy to add a minimal version as well.

[Docs] Supabase database

---

scripts/init.mjs

- Reinits git after deleting internal content during `init`, so that you have a clean repo to start with
- Updates the `update` script to ignore the same internal content that was excluded during init

Chore: cleaner git repo with init and update scripts

---

docs/migrations/authentication/better-auth.mdx

The existing `better-auth` docs were a little contrived.
I've updated with the commands/code that I've run on a fresh fork.

docs: add context to better-auth migration

---

turbo.json

To run clean tasks in repo, it is necessary to have the task declared in the turbo.json file. This PR simply adds the task to turbo.json

fix: clean tasks needed to be added to turbo.json

---

docs/addons/next-safe-action.mdx
docs/mint.json

Documentation on the proposal of adding Next Safe Action library as a recommendation on the addon page. To demonstrate further how good I believe next-safe-action is, I think it would be a good idea to write a recipe maybe on how to use secure your actions with the library, introduce logging, and rate limiting. However, I just do not know if a recipe is the correct location for such a guide. 
#321

Docs - next safe action Addon

---

docs/packages/notifications.mdx
packages/notifications/components/provider.tsx

I swapped the key used for the feed, and took an initial stab at creating some basic docs. Let me know if there should be more or less detail.

change key and stub docs

---

docs/setup/installation.mdx
package.json

This pull request updates the documentation by adding a link to the [Database Configuration Guide](https://docs.next-forge.com/packages/database#default-configuration) for Prisma configuration when using Neon. This ensures users have a clear reference for setting up their database correctly.
Closes #477 
No functional changes were made to the codebase; this is purely a documentation update to improve clarity for developers configuring their databases.

docs: add link to Prisma Database Configuration Guide

---

apps/storybook/.storybook/main.ts

This PR fixes the Storybook configuration by using createRequire to resolve package paths, The original code used require. The fix maintains the same package resolution functionality while being compatible with the file's ESM import syntax.
Closes #517

Fixed Build fails (Storybook) - fresh install #517

---

docs/packages/observability/debugging.mdx

Fix a typo in debugging.mdx

---

docs/migrations/authentication/better-auth.mdx

Add a missing step in better-auth migration doc page
Closes #474
Doc is about adding nextjs handlers setup with a `handlers.ts` file (in packages/auth). 
Re-exported on corresponding api endpoints in app folder of `apps/app`
EDIT: Exporting * from handlers fails because next wait for all functions types (DELETE, PATCH, etc...) so we only export GET & POST

Enhanced better-auth migration docs

---

docs/app/[[...slug]]/page.tsx
docs/app/global.css

Add mobile menu to the documentation site. 
(See: https://github.com/haydenbleasel/kibo/pull/151 , https://github.com/haydenbleasel/ultracite/pull/161)

add mobile menu
